// Importing the Stripe Publish Key from environment variables
import { stripePublishKey } from '@env';


export const constant = {
    // Stripe Publish Key: This key is used for client-side authentication with the Stripe API.
    // It is fetched from the environment variables defined in the .env file.
    stripePublishKey: stripePublishKey
}



export const countries = [
    { name: "Afghanistan", value: "Afghanistan" },
    { name: "Albania", value: "Albania" },
    { name: "Algeria", value: "Algeria" },
    { name: "Andorra", value: "Andorra" },
    { name: "Angola", value: "Angola" },
    { name: "Anguilla", value: "Anguilla" },
    { name: "Antigua &amp; Barbuda", value: "Antigua &amp; Barbuda" },
    { name: "Argentina", value: "Argentina" },
    { name: "Armenia", value: "Armenia" },
    { name: "Aruba", value: "Aruba" },
    { name: "Australia", value: "Australia" },
    { name: "Austria", value: "Austria" },
    { name: "Azerbaijan", value: "Azerbaijan" },
    { name: "Bahamas", value: "Bahamas" },
    { name: "Bahrain", value: "Bahrain" },
    { name: "Bangladesh", value: "Bangladesh" },
    { name: "Barbados", value: "Barbados" },
    { name: "Belarus", value: "Belarus" },
    { name: "Belgium", value: "Belgium" },
    { name: "Belize", value: "Belize" },
    { name: "Benin", value: "Benin" },
    { name: "Bermuda", value: "Bermuda" },
    { name: "Bhutan", value: "Bhutan" },
    { name: "Bolivia", value: "Bolivia" },
    { name: "Bosnia &amp; Herzegovina", value: "Bosnia &amp; Herzegovina" },
    { name: "Botswana", value: "Botswana" },
    { name: "Brazil", value: "Brazil" },
    { name: "British Virgin Islands", value: "British Virgin Islands" },
    { name: "Brunei", value: "Brunei" },
    { name: "Bulgaria", value: "Bulgaria" },
    { name: "Burkina Faso", value: "Burkina Faso" },
    { name: "Burundi", value: "Burundi" },
    { name: "Cambodia", value: "Cambodia" },
    { name: "Cameroon", value: "Cameroon" },
    { name: "Cape Verde", value: "Cape Verde" },
    { name: "Cayman Islands", value: "Cayman Islands" },
    { name: "Chad", value: "Chad" },
    { name: "Chile", value: "Chile" },
    { name: "China", value: "China" },
    { name: "Colombia", value: "Colombia" },
    { name: "Congo", value: "Congo" },
    { name: "Cook Islands", value: "Cook Islands" },
    { name: "Costa Rica", value: "Costa Rica" },
    { name: "Cote D Ivoire", value: "Cote D Ivoire" },
    { name: "Croatia", value: "Croatia" },
    { name: "Cruise Ship", value: "Cruise Ship" },
    { name: "Cuba", value: "Cuba" },
    { name: "Cyprus", value: "Cyprus" },
    { name: "Czech Republic", value: "Czech Republic" },
    { name: "Denmark", value: "Denmark" },
    { name: "Djibouti", value: "Djibouti" },
    { name: "Dominica", value: "Dominica" },
    { name: "Dominican Republic", value: "Dominican Republic" },
    { name: "Ecuador", value: "Ecuador" },
    { name: "Egypt", value: "Egypt" },
    { name: "El Salvador", value: "El Salvador" },
    { name: "Equatorial Guinea", value: "Equatorial Guinea" },
    { name: "Estonia", value: "Estonia" },
    { name: "Ethiopia", value: "Ethiopia" },
    { name: "Falkland Islands", value: "Falkland Islands" },
    { name: "Faroe Islands", value: "Faroe Islands" },
    { name: "Fiji", value: "Fiji" },
    { name: "Finland", value: "Finland" },
    { name: "France", value: "France" },
    { name: "French Polynesia", value: "French Polynesia" },
    { name: "French West Indies", value: "French West Indies" },
    { name: "Gabon", value: "Gabon" },
    { name: "Gambia", value: "Gambia" },
    { name: "Georgia", value: "Georgia" },
    { name: "Germany", value: "Germany" },
    { name: "Ghana", value: "Ghana" },
    { name: "Gibraltar", value: "Gibraltar" },
    { name: "Greece", value: "Greece" },
    { name: "Greenland", value: "Greenland" },
    { name: "Grenada", value: "Grenada" },
    { name: "Guam", value: "Guam" },
    { name: "Guatemala", value: "Guatemala" },
    { name: "Guernsey", value: "Guernsey" },
    { name: "Guinea", value: "Guinea" },
    { name: "Guinea Bissau", value: "Guinea Bissau" },
    { name: "Guyana", value: "Guyana" },
    { name: "Haiti", value: "Haiti" },
    { name: "Honduras", value: "Honduras" },
    { name: "Hong Kong", value: "Hong Kong" },
    { name: "Hungary", value: "Hungary" },
    { name: "Iceland", value: "Iceland" },
    { name: "India", value: "India" },
    { name: "Indonesia", value: "Indonesia" },
    { name: "Iran", value: "Iran" },
    { name: "Iraq", value: "Iraq" },
    { name: "Ireland", value: "Ireland" },
    { name: "Isle of Man", value: "Isle of Man" },
    { name: "Israel", value: "Israel" },
    { name: "Italy", value: "Italy" },
    { name: "Jamaica", value: "Jamaica" },
    { name: "Japan", value: "Japan" },
    { name: "Jersey", value: "Jersey" },
    { name: "Jordan", value: "Jordan" },
    { name: "Kazakhstan", value: "Kazakhstan" },
    { name: "Kenya", value: "Kenya" },
    { name: "Kuwait", value: "Kuwait" },
    { name: "Kyrgyz Republic", value: "Kyrgyz Republic" },
    { name: "Laos", value: "Laos" },
    { name: "Latvia", value: "Latvia" },
    { name: "Lebanon", value: "Lebanon" },
    { name: "Lesotho", value: "Lesotho" },
    { name: "Liberia", value: "Liberia" },
    { name: "Libya", value: "Libya" },
    { name: "Liechtenstein", value: "Liechtenstein" },
    { name: "Lithuania", value: "Lithuania" },
    { name: "Luxembourg", value: "Luxembourg" },
    { name: "Macau", value: "Macau" },
    { name: "Macedonia", value: "Macedonia" },
    { name: "Madagascar", value: "Madagascar" },
    { name: "Malawi", value: "Malawi" },
    { name: "Malaysia", value: "Malaysia" },
    { name: "Maldives", value: "Maldives" },
    { name: "Mali", value: "Mali" },
    { name: "Malta", value: "Malta" },
    { name: "Mauritania", value: "Mauritania" },
    { name: "Mauritius", value: "Mauritius" },
    { name: "Mexico", value: "Mexico" },
    { name: "Moldova", value: "Moldova" },
    { name: "Monaco", value: "Monaco" },
    { name: "Mongolia", value: "Mongolia" },
    { name: "Montenegro", value: "Montenegro" },
    { name: "Montserrat", value: "Montserrat" },
    { name: "Morocco", value: "Morocco" },
    { name: "Mozambique", value: "Mozambique" },
    { name: "Namibia", value: "Namibia" },
    { name: "Nepal", value: "Nepal" },
    { name: "Netherlands", value: "Netherlands" },
    { name: "Netherlands Antilles", value: "Netherlands Antilles" },
    { name: "New Caledonia", value: "New Caledonia" },
    { name: "New Zealand", value: "New Zealand" },
    { name: "Nicaragua", value: "Nicaragua" },
    { name: "Niger", value: "Niger" },
    { name: "Nigeria", value: "Nigeria" },
    { name: "Norway", value: "Norway" },
    { name: "Oman", value: "Oman" },
    { name: "Pakistan", value: "Pakistan" },
    { name: "Palestine", value: "Palestine" },
    { name: "Panama", value: "Panama" },
    { name: "Papua New Guinea", value: "Papua New Guinea" },
    { name: "Paraguay", value: "Paraguay" },
    { name: "Peru", value: "Peru" },
    { name: "Philippines", value: "Philippines" },
    { name: "Poland", value: "Poland" },
    { name: "Portugal", value: "Portugal" },
    { name: "Puerto Rico", value: "Puerto Rico" },
    { name: "Qatar", value: "Qatar" },
    { name: "Reunion", value: "Reunion" },
    { name: "Romania", value: "Romania" },
    { name: "Russia", value: "Russia" },
    { name: "Rwanda", value: "Rwanda" },
    { name: "Saint Pierre &amp; Miquelon", value: "Saint Pierre &amp; Miquelon" },
    { name: "Samoa", value: "Samoa" },
    { name: "San Marino", value: "San Marino" },
    { name: "Satellite", value: "Satellite" },
    { name: "Saudi Arabia", value: "Saudi Arabia" },
    { name: "Senegal", value: "Senegal" },
    { name: "Serbia", value: "Serbia" },
    { name: "Seychelles", value: "Seychelles" },
    { name: "Sierra Leone", value: "Sierra Leone" },
    { name: "Singapore", value: "Singapore" },
    { name: "Slovakia", value: "Slovakia" },
    { name: "Slovenia", value: "Slovenia" },
    { name: "South Africa", value: "South Africa" },
    { name: "South Korea", value: "South Korea" },
    { name: "Spain", value: "Spain" },
    { name: "Sri Lanka", value: "Sri Lanka" },
    { name: "St Kitts &amp; Nevis", value: "St Kitts &amp; Nevis" },
    { name: "St Lucia", value: "St Lucia" },
    { name: "St Vincent", value: "St Vincent" },
    { name: "St. Lucia", value: "St. Lucia" },
    { name: "Sudan", value: "Sudan" },
    { name: "Suriname", value: "Suriname" },
    { name: "Swaziland", value: "Swaziland" },
    { name: "Sweden", value: "Sweden" },
    { name: "Switzerland", value: "Switzerland" },
    { name: "Syria", value: "Syria" },
    { name: "Taiwan", value: "Taiwan" },
    { name: "Tajikistan", value: "Tajikistan" },
    { name: "Tanzania", value: "Tanzania" },
    { name: "Thailand", value: "Thailand" },
    { name: "Timor L'Este", value: "Timor L'Este" },
    { name: "Togo", value: "Togo" },
    { name: "Tonga", value: "Tonga" },
    { name: "Trinidad &amp; Tobago", value: "Trinidad &amp; Tobago" },
    { name: "Tunisia", value: "Tunisia" },
    { name: "Turkey", value: "Turkey" },
    { name: "Turkmenistan", value: "Turkmenistan" },
    { name: "Turks &amp; Caicos", value: "Turks &amp; Caicos" },
    { name: "Uganda", value: "Uganda" },
    { name: "Ukraine", value: "Ukraine" },
    { name: "United Arab Emirates", value: "United Arab Emirates" },
    { name: "United Kingdom", value: "United Kingdom" },
    { name: "Uruguay", value: "Uruguay" },
    { name: "Uzbekistan", value: "Uzbekistan" },
    { name: "Venezuela", value: "Venezuela" },
    { name: "Vietnam", value: "Vietnam" },
    { name: "Virgin Islands (US)", value: "Virgin Islands (US)" },
    { name: "Yemen", value: "Yemen" },
    { name: "Zambia", value: "Zambia" },
    { name: "Zimbabwe", value: "Zimbabwe" }
]
