
export const FontFamily = {
    black: 'Poppins-Black',
    blackItalic: 'Poppins-BlackItalic',
    bold: 'Poppins-Bold',
    boldItalic: 'Poppins-BoldItalic',
    extarBold: 'Poppins-ExtraBold',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    extraLight: 'Poppins-ExtraLight',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    italic: 'Poppins-Italic',
    light: 'Poppins-Light',
    lightItalic: 'Poppins-LightItalic',
    medium: 'Poppins-Medium',
    mediumItalic: 'Poppins-MediumItalic',
    regular: 'Poppins-Regular',
    semiBold: 'Poppins-SemiBold',
    semiBoldItalic: 'Poppins-SemiBoldItalic',
    thin: 'Poppins-Thin',
    thinItalic: 'Poppins-ThinItalic',
    interBold: 'Inter-Bold',
    interBlack: 'Inter-Black',
    interExtraBold: 'Inter-ExtraBold',
    interExtraLight: 'Inter-ExtraLight',
    interLight: 'Inter-Light',
    interMedium: 'Inter-Medium',
    interRegular: 'Inter-Regular',
    interSemiBold: 'Inter-SemiBold',
    interThin: 'Inter-Thin',
}