// Import necessary functions from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';
import { logoutUser } from '../thunk'; // Importing thunk for user logout

// Initial state of the app users slice
const initialState = {
  data: {} // Placeholder for user data
}

// Creating a Redux slice for managing app users
export const appUsersSlice = createSlice({
  name: 'user', // Slice name
  initialState: initialState, // Initial state
  reducers: {
    // Reducer function to handle user login
    handleLogin: (state, action) => {
      state.data = action.payload; // Update user data with login payload
    },
    // Reducer function to handle user logout
    handleLogout: (state, action) => {
      state.data = initialState.data; // Reset user data to initial state
    },
  },
  extraReducers: builder => {
    // Handling extra reducers for asynchronous user logout
    builder.addCase(logoutUser.fulfilled, (state, _action) => {
      state.data = initialState.data; // Reset user data to initial state
    })
  }
})

// Exporting the action creator functions generated by the slice
export const { handleLogin, handleLogout } = appUsersSlice.actions;

// Exporting the reducer function generated by the slice
export default appUsersSlice.reducer;
